package Form;

import DAO.ChuyenDeDAO;
import DAO.NhanVienDAO;
import Entity.ChuyenDe;
import Entity.NhanVien;
import ThuVien.Auth;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author nguyenvanquyet
 */
public class DangNhap extends javax.swing.JDialog {

    boolean flag = false;

    /**
     * Creates new form DangNhap1
     */
    NhanVienDAO dao = new NhanVienDAO();

    public DangNhap() {
        initComponents();
        setLocationRelativeTo(this);
    }


    void dangNhap() {
        if (kiemthu() == false) {
            return;
        }
        String manv = txtmaNV.getText();
        String matkhau = new String(txtmatkhau.getPassword());
        NhanVien nhanvien = dao.selectById(manv);
        if (nhanvien == null) {
            JOptionPane.showMessageDialog(this, "Sai tên đăng nhâp");
        } else if (!matkhau.equals(nhanvien.getMatKhau())) {
            JOptionPane.showMessageDialog(this, "Sai mật khẩu");
        } else {
            JOptionPane.showMessageDialog(this, "Đăng nhập thành công");
            Auth.user = nhanvien;
            new ManHinhChinh().setVisible(true);
            this.dispose();
            
        }
    }

    boolean kiemthu() {
        String s = txtmatkhau.getText();
        if (txtmaNV.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Tài khoản không được bỏ trống");
            return false;
        }
        if (txtmatkhau.getText().equals("")) {
            JOptionPane.showMessageDialog(this, " Mật khẩu không được bỏ trống");
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtmaNV = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtmatkhau = new javax.swing.JPasswordField();
        btndangnhap = new javax.swing.JButton();
        btnketthuc = new javax.swing.JButton();
        btnconmat = new javax.swing.JToggleButton();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/conongggggggggggggg (1).png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Tên đăng nhập");

        txtmaNV.setText("TeoNV");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Mật khẩu");

        txtmatkhau.setText("123456");

        btndangnhap.setBackground(new java.awt.Color(153, 153, 153));
        btndangnhap.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btndangnhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Key.png"))); // NOI18N
        btndangnhap.setText("Đăng nhập");
        btndangnhap.setMaximumSize(new java.awt.Dimension(117, 90));
        btndangnhap.setMinimumSize(new java.awt.Dimension(117, 90));
        btndangnhap.setPreferredSize(new java.awt.Dimension(117, 90));
        btndangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndangnhapActionPerformed(evt);
            }
        });

        btnketthuc.setBackground(new java.awt.Color(153, 153, 153));
        btnketthuc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnketthuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Exit.png"))); // NOI18N
        btnketthuc.setText("Kết Thúc");
        btnketthuc.setMaximumSize(new java.awt.Dimension(117, 90));
        btnketthuc.setMinimumSize(new java.awt.Dimension(117, 90));
        btnketthuc.setPreferredSize(new java.awt.Dimension(117, 90));
        btnketthuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnketthucActionPerformed(evt);
            }
        });

        btnconmat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/rsz_mở_mắt.png"))); // NOI18N
        btnconmat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconmatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtmaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btndangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btnketthuc, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtmatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnconmat)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(12, 12, 12)
                        .addComponent(txtmaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnconmat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btndangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnketthuc, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnketthucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnketthucActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(this, "Bạn có muốn kết thúc không ?", "", JOptionPane.YES_NO_OPTION);
        if (a == JOptionPane.YES_OPTION) {
            System.exit(0);
        }

    }//GEN-LAST:event_btnketthucActionPerformed

    private void btndangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndangnhapActionPerformed
        // TODO add your handling code here:
        dangNhap();
    }//GEN-LAST:event_btndangnhapActionPerformed

    private void btnconmatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconmatActionPerformed
        // TODO add your handling code here:
//
//          if (btnconmat.isSelected()) {
//            txtmatkhau.setEchoChar((char) 0);
//            btnconmat.setIcon(new ImageIcon("H:\\MonDuAnMau\\BaiTap\\DuAnMau\\src\\main\\resources\\Hinh\\rsz_mở_mắt"));
//        } else {
//            txtmatkhau.setEchoChar('*');
//            btnconmat.setIcon(new ImageIcon("H:\\MonDuAnMau\\BaiTap\\DuAnMau\\src\\main\\resources\\Hinh\\rsz_nhắm_mắt"));
//        }
        flag = !flag;
        if (flag) {
            txtmatkhau.setEchoChar('\u0000');
            btnconmat.setIcon(new ImageIcon("H:\\MonDuAnMau\\BaiTap\\DuAnMau\\src\\main\\resources\\Hinh\\rsz_mở_mắt.png"));
        } else {
            txtmatkhau.setEchoChar('*');
            btnconmat.setIcon(new ImageIcon("H:\\MonDuAnMau\\BaiTap\\DuAnMau\\src\\main\\resources\\Hinh\\rsz_nhắm_mắt.png"));

        }
    }//GEN-LAST:event_btnconmatActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnconmat;
    private javax.swing.JButton btndangnhap;
    private javax.swing.JButton btnketthuc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField txtmaNV;
    private javax.swing.JPasswordField txtmatkhau;
    // End of variables declaration//GEN-END:variables
}
