/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form;

import ClassIcon.Xlmage;
import ThuVien.Auth;
import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author nguyenvanquyet
 */
public class ManHinhChinh extends javax.swing.JFrame {

    /**
     * Creates new form ManHinhChinh
     */
    public ManHinhChinh() {
        initComponents();
        setLocationRelativeTo(this);
        setTitle("HỆ THỐNG QUẢN LÝ ĐÀO TẠO");
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu10 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jSeparator2 = new javax.swing.JSeparator();
        jMenuItem8 = new javax.swing.JMenuItem();
        jToolBar1 = new javax.swing.JToolBar();
        btndangXuatmanhinhchinh = new javax.swing.JButton();
        btnketThucmanhinhchinh = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnchuyenDemanhinhchinh = new javax.swing.JButton();
        btnnguoiHocManhinhchinh = new javax.swing.JButton();
        btnkhoaHocManhinhchinh = new javax.swing.JButton();
        btnhocVienManhinhchinh = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnhuongDanManhinhchinh = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbltime = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        btndangNhap = new javax.swing.JMenuItem();
        btndangXuat = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        btndoiMatKhau = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        btnketThuc = new javax.swing.JMenuItem();
        btnchuyenDe = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        btnkhoaHoc = new javax.swing.JMenuItem();
        btnnguoiHoc = new javax.swing.JMenuItem();
        btnhocVien = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        btnnhanVien = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        btnbangDiem = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        btnluongNguoiHoc = new javax.swing.JMenuItem();
        btndiemChuyenDe = new javax.swing.JMenuItem();
        btndoanhThu = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        btnhuongDan = new javax.swing.JMenuItem();
        btngioiThieuSanPham = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("File");
        jMenuBar3.add(jMenu6);

        jMenu7.setText("Edit");
        jMenuBar3.add(jMenu7);

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenu10.setText("File");
        jMenuBar4.add(jMenu10);

        jMenu11.setText("Edit");
        jMenuBar4.add(jMenu11);

        jMenuItem8.setText("jMenuItem8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setName("Hệ Thống Quản Lý Đào Tạo"); // NOI18N

        jToolBar1.setBackground(new java.awt.Color(204, 204, 204));
        jToolBar1.setRollover(true);

        btndangXuatmanhinhchinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Log out.png"))); // NOI18N
        btndangXuatmanhinhchinh.setText("Đăng Xuất");
        btndangXuatmanhinhchinh.setFocusable(false);
        btndangXuatmanhinhchinh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btndangXuatmanhinhchinh.setMaximumSize(new java.awt.Dimension(70, 60));
        btndangXuatmanhinhchinh.setPreferredSize(new java.awt.Dimension(70, 52));
        btndangXuatmanhinhchinh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btndangXuatmanhinhchinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btndangXuatmanhinhchinhMouseClicked(evt);
            }
        });
        btndangXuatmanhinhchinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndangXuatmanhinhchinhActionPerformed(evt);
            }
        });
        jToolBar1.add(btndangXuatmanhinhchinh);

        btnketThucmanhinhchinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Stop.png"))); // NOI18N
        btnketThucmanhinhchinh.setText("Kết Thúc");
        btnketThucmanhinhchinh.setFocusable(false);
        btnketThucmanhinhchinh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnketThucmanhinhchinh.setMaximumSize(new java.awt.Dimension(70, 60));
        btnketThucmanhinhchinh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnketThucmanhinhchinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnketThucmanhinhchinhActionPerformed(evt);
            }
        });
        jToolBar1.add(btnketThucmanhinhchinh);

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.add(jSeparator1);

        btnchuyenDemanhinhchinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Lists.png"))); // NOI18N
        btnchuyenDemanhinhchinh.setText("Chuyên Đề");
        btnchuyenDemanhinhchinh.setFocusable(false);
        btnchuyenDemanhinhchinh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnchuyenDemanhinhchinh.setMaximumSize(new java.awt.Dimension(70, 60));
        btnchuyenDemanhinhchinh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnchuyenDemanhinhchinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchuyenDemanhinhchinhActionPerformed(evt);
            }
        });
        jToolBar1.add(btnchuyenDemanhinhchinh);

        btnnguoiHocManhinhchinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Conference.png"))); // NOI18N
        btnnguoiHocManhinhchinh.setText("Người Học");
        btnnguoiHocManhinhchinh.setFocusable(false);
        btnnguoiHocManhinhchinh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnnguoiHocManhinhchinh.setMaximumSize(new java.awt.Dimension(70, 60));
        btnnguoiHocManhinhchinh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnnguoiHocManhinhchinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnguoiHocManhinhchinhActionPerformed(evt);
            }
        });
        jToolBar1.add(btnnguoiHocManhinhchinh);

        btnkhoaHocManhinhchinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Certificate.png"))); // NOI18N
        btnkhoaHocManhinhchinh.setText("Khóa Học");
        btnkhoaHocManhinhchinh.setFocusable(false);
        btnkhoaHocManhinhchinh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnkhoaHocManhinhchinh.setMaximumSize(new java.awt.Dimension(70, 60));
        btnkhoaHocManhinhchinh.setMinimumSize(new java.awt.Dimension(70, 60));
        btnkhoaHocManhinhchinh.setPreferredSize(new java.awt.Dimension(70, 60));
        btnkhoaHocManhinhchinh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnkhoaHocManhinhchinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkhoaHocManhinhchinhActionPerformed(evt);
            }
        });
        jToolBar1.add(btnkhoaHocManhinhchinh);

        btnhocVienManhinhchinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/User.png"))); // NOI18N
        btnhocVienManhinhchinh.setText("Học Viên");
        btnhocVienManhinhchinh.setFocusable(false);
        btnhocVienManhinhchinh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnhocVienManhinhchinh.setMaximumSize(new java.awt.Dimension(70, 60));
        btnhocVienManhinhchinh.setMinimumSize(new java.awt.Dimension(70, 60));
        btnhocVienManhinhchinh.setPreferredSize(new java.awt.Dimension(70, 60));
        btnhocVienManhinhchinh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnhocVienManhinhchinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhocVienManhinhchinhActionPerformed(evt);
            }
        });
        jToolBar1.add(btnhocVienManhinhchinh);
        jToolBar1.add(jSeparator3);

        btnhuongDanManhinhchinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Globe.png"))); // NOI18N
        btnhuongDanManhinhchinh.setText("Hướng Dẫn");
        btnhuongDanManhinhchinh.setFocusable(false);
        btnhuongDanManhinhchinh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnhuongDanManhinhchinh.setMaximumSize(new java.awt.Dimension(72, 60));
        btnhuongDanManhinhchinh.setMinimumSize(new java.awt.Dimension(72, 60));
        btnhuongDanManhinhchinh.setPreferredSize(new java.awt.Dimension(72, 60));
        btnhuongDanManhinhchinh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnhuongDanManhinhchinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhuongDanManhinhchinhActionPerformed(evt);
            }
        });
        jToolBar1.add(btnhuongDanManhinhchinh);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/anhongpoly.png"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.setForeground(new java.awt.Color(153, 153, 153));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Info.png"))); // NOI18N
        jLabel2.setText("Hệ quản lý đào tạo");

        lbltime.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Alarm.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbltime)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbltime)))
        );

        jMenu2.setText("Hệ Thống");

        btndangNhap.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btndangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Key.png"))); // NOI18N
        btndangNhap.setText("Đăng Nhập");
        btndangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndangNhapActionPerformed(evt);
            }
        });
        jMenu2.add(btndangNhap);

        btndangXuat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btndangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Exit.png"))); // NOI18N
        btndangXuat.setText("Đăng Xuất");
        btndangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndangXuatActionPerformed(evt);
            }
        });
        jMenu2.add(btndangXuat);
        jMenu2.add(jSeparator5);

        btndoiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Refresh.png"))); // NOI18N
        btndoiMatKhau.setText("Đổi Mật Khẩu");
        btndoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndoiMatKhauActionPerformed(evt);
            }
        });
        jMenu2.add(btndoiMatKhau);
        jMenu2.add(jSeparator6);

        btnketThuc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        btnketThuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Stop.png"))); // NOI18N
        btnketThuc.setText("Kết Thúc");
        btnketThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnketThucActionPerformed(evt);
            }
        });
        jMenu2.add(btnketThuc);

        jMenuBar1.add(jMenu2);

        btnchuyenDe.setText("Quản Lý");

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Lists.png"))); // NOI18N
        jMenuItem9.setText("Chuyên Đề");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        btnchuyenDe.add(jMenuItem9);

        btnkhoaHoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btnkhoaHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Certificate.png"))); // NOI18N
        btnkhoaHoc.setText("Khóa Học");
        btnkhoaHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkhoaHocActionPerformed(evt);
            }
        });
        btnchuyenDe.add(btnkhoaHoc);

        btnnguoiHoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btnnguoiHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Conference.png"))); // NOI18N
        btnnguoiHoc.setText("Người Học");
        btnnguoiHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnguoiHocActionPerformed(evt);
            }
        });
        btnchuyenDe.add(btnnguoiHoc);

        btnhocVien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btnhocVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/User.png"))); // NOI18N
        btnhocVien.setText("Học Viên");
        btnhocVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhocVienActionPerformed(evt);
            }
        });
        btnchuyenDe.add(btnhocVien);
        btnchuyenDe.add(jSeparator4);

        btnnhanVien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btnnhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Users.png"))); // NOI18N
        btnnhanVien.setText("Nhân Viên");
        btnnhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnhanVienActionPerformed(evt);
            }
        });
        btnchuyenDe.add(btnnhanVien);

        jMenuBar1.add(btnchuyenDe);

        jMenu8.setText("Thống Kê");

        btnbangDiem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.ALT_DOWN_MASK));
        btnbangDiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Card file.png"))); // NOI18N
        btnbangDiem.setText("Bảng Điểm");
        btnbangDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbangDiemActionPerformed(evt);
            }
        });
        jMenu8.add(btnbangDiem);
        jMenu8.add(jSeparator7);

        btnluongNguoiHoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.ALT_DOWN_MASK));
        btnluongNguoiHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Clien list.png"))); // NOI18N
        btnluongNguoiHoc.setText("Lượng Người Học");
        btnluongNguoiHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnluongNguoiHocActionPerformed(evt);
            }
        });
        jMenu8.add(btnluongNguoiHoc);

        btndiemChuyenDe.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.ALT_DOWN_MASK));
        btndiemChuyenDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Best.png"))); // NOI18N
        btndiemChuyenDe.setText("Điểm Chuyển Đề");
        btndiemChuyenDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndiemChuyenDeActionPerformed(evt);
            }
        });
        jMenu8.add(btndiemChuyenDe);

        btndoanhThu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        btndoanhThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Dollar.png"))); // NOI18N
        btndoanhThu.setText("Doanh Thu");
        btndoanhThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndoanhThuActionPerformed(evt);
            }
        });
        jMenu8.add(btndoanhThu);

        jMenuBar1.add(jMenu8);

        jMenu9.setText("Trợ Giúp");

        btnhuongDan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        btnhuongDan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Globe.png"))); // NOI18N
        btnhuongDan.setText("Hướng Dẫn Sử Dụng");
        btnhuongDan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhuongDanActionPerformed(evt);
            }
        });
        jMenu9.add(btnhuongDan);

        btngioiThieuSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Home.png"))); // NOI18N
        btngioiThieuSanPham.setText("Giới Thiệu Sản Phẩm");
        btngioiThieuSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngioiThieuSanPhamActionPerformed(evt);
            }
        });
        jMenu9.add(btngioiThieuSanPham);

        jMenuBar1.add(jMenu9);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 731, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndangXuatmanhinhchinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndangXuatmanhinhchinhActionPerformed
        // TODO add your handling code here:
        OpenDangNhap();        // TODO add your handling code here:

    }//GEN-LAST:event_btndangXuatmanhinhchinhActionPerformed

    private void btnketThucmanhinhchinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnketThucmanhinhchinhActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(this, "Bạn có muốn kết thúc không ?", "", JOptionPane.YES_NO_OPTION);
        if (a == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnketThucmanhinhchinhActionPerformed

    private void btnkhoaHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkhoaHocActionPerformed
        OpenQuanLyKhoaHoc();        // TODO add your handling code here:
    }//GEN-LAST:event_btnkhoaHocActionPerformed

    private void btndangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndangNhapActionPerformed
        OpenDangNhap();      // TODO add your handling code here:
    }//GEN-LAST:event_btndangNhapActionPerformed

    private void btndangXuatmanhinhchinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndangXuatmanhinhchinhMouseClicked
    }//GEN-LAST:event_btndangXuatmanhinhchinhMouseClicked

    private void btnchuyenDemanhinhchinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchuyenDemanhinhchinhActionPerformed
        OpenChuyenDe();        // TODO add your handling code here:
    }//GEN-LAST:event_btnchuyenDemanhinhchinhActionPerformed

    private void btndoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndoiMatKhauActionPerformed
        // TODO add your handling code here:
        OpenDoiMatKhau();
    }//GEN-LAST:event_btndoiMatKhauActionPerformed

    private void btnhocVienManhinhchinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhocVienManhinhchinhActionPerformed
        // TODO add your handling code here:
        OpenQuanLyHocVien();
    }//GEN-LAST:event_btnhocVienManhinhchinhActionPerformed

    private void btnkhoaHocManhinhchinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkhoaHocManhinhchinhActionPerformed
        // TODO add your handling code here:
        OpenQuanLyKhoaHoc();
    }//GEN-LAST:event_btnkhoaHocManhinhchinhActionPerformed

    private void btnnhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnhanVienActionPerformed
        // TODO add your handling code here:
        OpenQuanLyNhanVien();
    }//GEN-LAST:event_btnnhanVienActionPerformed

    private void btnnguoiHocManhinhchinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnguoiHocManhinhchinhActionPerformed
        // TODO add your handling code here:
        OpenQuanLyNguoiHoc();
    }//GEN-LAST:event_btnnguoiHocManhinhchinhActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        OpenChuyenDe();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void btnnguoiHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnguoiHocActionPerformed
        // TODO add your handling code here:
        OpenQuanLyNguoiHoc();
    }//GEN-LAST:event_btnnguoiHocActionPerformed

    private void btnhocVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhocVienActionPerformed

        OpenQuanLyHocVien();        // TODO add your handling code here:
    }//GEN-LAST:event_btnhocVienActionPerformed

    private void btnketThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnketThucActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(this, "Bạn có muốn kết thúc không ?", "", JOptionPane.YES_NO_OPTION);
        if (a == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnketThucActionPerformed

    private void btnbangDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbangDiemActionPerformed
        // TODO add your handling code here:
        Openthongke(0);
    }//GEN-LAST:event_btnbangDiemActionPerformed

    private void btnhuongDanManhinhchinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhuongDanManhinhchinhActionPerformed
        OpenHuongDan();        // TODO add your handling code here:
    }//GEN-LAST:event_btnhuongDanManhinhchinhActionPerformed

    private void btnluongNguoiHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnluongNguoiHocActionPerformed
        Openthongke(1);  // TODO add your handling code here:
    }//GEN-LAST:event_btnluongNguoiHocActionPerformed

    private void btndiemChuyenDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndiemChuyenDeActionPerformed
        Openthongke(2);        // TODO add your handling code here:
    }//GEN-LAST:event_btndiemChuyenDeActionPerformed

    private void btndoanhThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndoanhThuActionPerformed
        Openthongke(3);        // TODO add your handling code here:
    }//GEN-LAST:event_btndoanhThuActionPerformed

    private void btndangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndangXuatActionPerformed
        OpenDangNhap();        // TODO add your handling code here:
    }//GEN-LAST:event_btndangXuatActionPerformed

    private void btnhuongDanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhuongDanActionPerformed
        OpenHuongDan();        // TODO add your handling code here:
    }//GEN-LAST:event_btnhuongDanActionPerformed

    private void btngioiThieuSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngioiThieuSanPhamActionPerformed
OpenHuongDan();        // TODO add your handling code here:
    }//GEN-LAST:event_btngioiThieuSanPhamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManHinhChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManHinhChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManHinhChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManHinhChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManHinhChinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnbangDiem;
    private javax.swing.JMenu btnchuyenDe;
    private javax.swing.JButton btnchuyenDemanhinhchinh;
    private javax.swing.JMenuItem btndangNhap;
    private javax.swing.JMenuItem btndangXuat;
    private javax.swing.JButton btndangXuatmanhinhchinh;
    private javax.swing.JMenuItem btndiemChuyenDe;
    private javax.swing.JMenuItem btndoanhThu;
    private javax.swing.JMenuItem btndoiMatKhau;
    private javax.swing.JMenuItem btngioiThieuSanPham;
    private javax.swing.JMenuItem btnhocVien;
    private javax.swing.JButton btnhocVienManhinhchinh;
    private javax.swing.JMenuItem btnhuongDan;
    private javax.swing.JButton btnhuongDanManhinhchinh;
    private javax.swing.JMenuItem btnketThuc;
    private javax.swing.JButton btnketThucmanhinhchinh;
    private javax.swing.JMenuItem btnkhoaHoc;
    private javax.swing.JButton btnkhoaHocManhinhchinh;
    private javax.swing.JMenuItem btnluongNguoiHoc;
    private javax.swing.JMenuItem btnnguoiHoc;
    private javax.swing.JButton btnnguoiHocManhinhchinh;
    private javax.swing.JMenuItem btnnhanVien;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lbltime;
    // End of variables declaration//GEN-END:variables

    private void init() {
       // setIconImage(Xlmage.getApplcon());
        //  new ChaoUngDung(this, true).setVisible(true);
        //  new DangNhap(this, true).setVisible(true);
        new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date now = new Date();
                SimpleDateFormat time = new SimpleDateFormat("hh:mm:ss a");
                String test = time.format(now);
                lbltime.setText(test);
            }

        }).start();

    }

    public void Openthongke(int index) {
        if (Auth.isLogin()) {
            if (index == 3 && !Auth.isManager()) {
                JOptionPane.showMessageDialog(this, "Bạn không có quyền xem thông tin doanh thu");
                return;
            } else {
                TongHopVaThongKe1 tkwin = new TongHopVaThongKe1(this, true);
                tkwin.select(index);
                tkwin.setVisible(true);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng đăng nhập");
            return;
        }
    }

    public void OpenHuongDan() {
        try {
            File htmlFile = new File("H:\\MonDuAnMau\\BaiTap\\DuAnMau\\src\\main\\java\\Help\\index.html"); // Thay đổi đường dẫn tới tệp HTML của bạn
            Desktop.getDesktop().browse(htmlFile.toURI());
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(this, "Không tìm thấy file hướng dẫn");
        }
    }

    public void OpenDangNhap() {
        new DangNhap().setVisible(true);
        ManHinhChinh.this.dispose();
        return;
    }

    public void OpenChuyenDe() {
        new QuanLyChuyenDe(this, true).setVisible(true);
        return;
    }

    public void OpenDoiMatKhau() {
        new DoiMatKhau(this, true).setVisible(true);
        return;
    }

    public void OpenQuanLyHocVien() {
        new QuanLyHocVien(this, true).setVisible(true);
        return;
    }

    public void OpenQuanLyKhoaHoc() {
        new QuanLyKhoaHoc(this, true).setVisible(true);
        return;
    }

    public void OpenQuanLyNhanVien() {
        new QuanLyNhanVien(this, true).setVisible(true);
        return;
    }

    public void OpenQuanLyNguoiHoc() {
        new QuanLyNguoiHoc(this, true).setVisible(true);
        return;
    }

    public void TongHopVaThongke1() {
        new TongHopVaThongKe1(this, true).setVisible(true);
        return;
    }
}
