/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Form;

import ClassIcon.Xlmage;
import DAO.ChuyenDeDAO;
import Entity.ChuyenDe;
import Entity.NhanVien;
import ThuVien.Auth;
import ThuVien.DialogHelper;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.plaf.FileChooserUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nguyenvanquyet
 */
public class QuanLyChuyenDe extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */
    ChuyenDeDAO dao = new ChuyenDeDAO();
    JFileChooser filechooser = new JFileChooser();
    int row = -1;

    public QuanLyChuyenDe(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);
        filltotable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tabs = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablequanLyNguoiHoc = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtmaChuyenDe = new javax.swing.JTextField();
        txttenChuyenDe = new javax.swing.JTextField();
        txtthoiLuongGio = new javax.swing.JTextField();
        txthocPhi = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtmoTaChuyenDe = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();
        trai1 = new javax.swing.JButton();
        trai2 = new javax.swing.JButton();
        phai1 = new javax.swing.JButton();
        phai2 = new javax.swing.JButton();
        lblhinhLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("QUẢN LÝ CHUYÊN ĐỀ");

        tablequanLyNguoiHoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã CD", "Tên CD", "Học Phí", "Thời lượng", "Hình"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablequanLyNguoiHoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablequanLyNguoiHocMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablequanLyNguoiHoc);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        tabs.addTab("DANH SÁCH", jPanel2);

        jPanel5.setMaximumSize(new java.awt.Dimension(32767, 32900));
        jPanel5.setPreferredSize(new java.awt.Dimension(532, 400));

        jLabel11.setText("Hình logo");

        jLabel3.setText("Mã chuyên đề");

        jLabel4.setText("Tên chuyên đề");

        jLabel5.setText("Thời lượng (giờ)");

        jLabel6.setText("Học phí");

        txtmoTaChuyenDe.setColumns(20);
        txtmoTaChuyenDe.setRows(5);
        jScrollPane3.setViewportView(txtmoTaChuyenDe);

        jLabel7.setText("Mô tả chuyên đề");

        btnThem.setText("Thêm");
        btnThem.setMaximumSize(new java.awt.Dimension(60, 31));
        btnThem.setMinimumSize(new java.awt.Dimension(60, 31));
        btnThem.setPreferredSize(new java.awt.Dimension(60, 31));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.setMaximumSize(new java.awt.Dimension(60, 31));
        btnSua.setMinimumSize(new java.awt.Dimension(60, 31));
        btnSua.setPreferredSize(new java.awt.Dimension(60, 31));
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.setMaximumSize(new java.awt.Dimension(60, 31));
        btnXoa.setMinimumSize(new java.awt.Dimension(60, 31));
        btnXoa.setPreferredSize(new java.awt.Dimension(60, 31));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnMoi.setText("Mới");
        btnMoi.setMaximumSize(new java.awt.Dimension(60, 31));
        btnMoi.setMinimumSize(new java.awt.Dimension(60, 31));
        btnMoi.setPreferredSize(new java.awt.Dimension(60, 31));
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        trai1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/trai2.png"))); // NOI18N
        trai1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trai1ActionPerformed(evt);
            }
        });

        trai2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/trai1.png"))); // NOI18N
        trai2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trai2ActionPerformed(evt);
            }
        });

        phai1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/phai1.png"))); // NOI18N
        phai1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phai1ActionPerformed(evt);
            }
        });

        phai2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/phai2.png"))); // NOI18N
        phai2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phai2ActionPerformed(evt);
            }
        });

        lblhinhLogo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblhinhLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblhinhLogoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblhinhLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel3))
                            .addComponent(txtmaChuyenDe, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttenChuyenDe, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(txtthoiLuongGio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txthocPhi, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(trai1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(trai2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(phai1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(phai2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtmaChuyenDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txttenChuyenDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtthoiLuongGio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6))
                    .addComponent(lblhinhLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txthocPhi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(trai1)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(trai2)
                    .addComponent(phai1)
                    .addComponent(phai2))
                .addContainerGap())
        );

        tabs.addTab("CẬP NHẬT", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabs, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabs, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablequanLyNguoiHocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablequanLyNguoiHocMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            this.row = tablequanLyNguoiHoc.getSelectedRow();
            this.edit();
        }
    }//GEN-LAST:event_tablequanLyNguoiHocMouseClicked

    private void lblhinhLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblhinhLogoMouseClicked
        chonAnh();
        // TODO add your handling code here:
    }//GEN-LAST:event_lblhinhLogoMouseClicked

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        clearform();        // TODO add your handling code here:
    }//GEN-LAST:event_btnMoiActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        insert();        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        delete();        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        update();// TODO add your handling code here:
    }//GEN-LAST:event_btnSuaActionPerformed

    private void trai1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trai1ActionPerformed
        first();        // TODO add your handling code here:
    }//GEN-LAST:event_trai1ActionPerformed

    private void trai2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trai2ActionPerformed
        prev();        // TODO add your handling code here:
    }//GEN-LAST:event_trai2ActionPerformed

    private void phai1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phai1ActionPerformed
        next();        // TODO add your handling code here:
    }//GEN-LAST:event_phai1ActionPerformed

    private void phai2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phai2ActionPerformed
        last();        // TODO add your handling code here:
    }//GEN-LAST:event_phai2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyChuyenDe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyChuyenDe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyChuyenDe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyChuyenDe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QuanLyChuyenDe dialog = new QuanLyChuyenDe(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblhinhLogo;
    private javax.swing.JButton phai1;
    private javax.swing.JButton phai2;
    private javax.swing.JTable tablequanLyNguoiHoc;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JButton trai1;
    private javax.swing.JButton trai2;
    private javax.swing.JTextField txthocPhi;
    private javax.swing.JTextField txtmaChuyenDe;
    private javax.swing.JTextArea txtmoTaChuyenDe;
    private javax.swing.JTextField txttenChuyenDe;
    private javax.swing.JTextField txtthoiLuongGio;
    // End of variables declaration//GEN-END:variables
    void filltotable() {
        DefaultTableModel model = (DefaultTableModel) tablequanLyNguoiHoc.getModel();
        model.setRowCount(0);
        try {
            List<ChuyenDe> list = dao.selectAll();
            for (ChuyenDe cd : list) {
                Object[] row = {cd.getMaCD(), cd.getTenCD(), cd.getHocPhi(), cd.getThoiLuong(), cd.getHinh(), cd.getMoTa(),};
                model.addRow(row);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi");
        }
    }

    void chonAnh() {
        if (filechooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = filechooser.getSelectedFile();
            ThuVien.Xlmage.save(file);//lưu hình vào thư mục logo
            ImageIcon icon = ThuVien.Xlmage.read(file.getName());//đọc hình ảnh từ logo
            lblhinhLogo.setIcon(icon);
            lblhinhLogo.setToolTipText(file.getName());//giữ tên hình tooltip
        }
    }

    void clearform() {
        ChuyenDe cd = new ChuyenDe();
        this.setForm(cd);
        this.row = -1;
        this.updateStatus();
        lblhinhLogo.setIcon(null);
    }

    void setForm(ChuyenDe cd) {
        txtmaChuyenDe.setText(cd.getMaCD());
        txttenChuyenDe.setText(cd.getTenCD());
        txtthoiLuongGio.setText(String.valueOf(cd.getThoiLuong()));
        txthocPhi.setText(String.valueOf(cd.getHocPhi()));
        txtmoTaChuyenDe.setText(cd.getMoTa());
        if (cd.getHinh() != null) {
            lblhinhLogo.setToolTipText(cd.getHinh());
            lblhinhLogo.setIcon(ThuVien.Xlmage.read(cd.getHinh()));
        }
    }

    ChuyenDe getForm() {
        ChuyenDe cd = new ChuyenDe();
        cd.setMaCD(txtmaChuyenDe.getText());
        cd.setTenCD(txttenChuyenDe.getText());
        cd.setMoTa(txtmoTaChuyenDe.getText());
        cd.setHinh(lblhinhLogo.getToolTipText());
        cd.setThoiLuong(Integer.valueOf(txtthoiLuongGio.getText()));
        cd.setHocPhi(Double.valueOf(txthocPhi.getText()));
        return cd;
    }

    void insert() {
        if (kiemThu() == false) {
            return;
        }
        ChuyenDe cd = getForm();
        List<ChuyenDe> list = dao.selectAll();
        for (ChuyenDe chuyende : list) {
            if (txtmaChuyenDe.getText().equals(chuyende.getMaCD())) {
                JOptionPane.showMessageDialog(this, "Mã chuyên đề trùng");
                return;
            }
        }

        try {
            dao.insert(cd);
            this.filltotable();
            this.clearform();
            DialogHelper.alert(this, "Thêm mới thành công!");
        } catch (Exception e) {
            DialogHelper.alert(this, "Thêm mới thất bại!");
            System.out.println(e);
        }
    }

    void delete() {
        String macd = txtmaChuyenDe.getText();
        try {
            dao.delete(macd);
            this.filltotable();
            this.clearform();
            DialogHelper.alert(this, "Xóa thành công!");
        } catch (Exception e) {
            DialogHelper.alert(this, "Xóa thất bại!");
        }
    }

    void update() {
        ChuyenDe cd = getForm();
        try {
            dao.update(cd);
            this.filltotable();
            DialogHelper.alert(this, "Cập nhật thành công!");
        } catch (Exception e) {
            DialogHelper.alert(this, "Cập nhật thất bại!");
        }
    }

    void edit() {
        try {
            String macd = (String) tablequanLyNguoiHoc.getValueAt(this.row, 0);
            ChuyenDe cd = dao.selectById(macd);
            if (cd != null) {
                this.setForm(cd);
                tabs.setSelectedIndex(1);
                this.updateStatus();
            }
        } catch (Exception e) {
            DialogHelper.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }

    void updateStatus() {
        boolean insertable = (this.row >= 0);
        boolean first = (this.row == 0);
        boolean last = (this.row == tablequanLyNguoiHoc.getRowCount() - 1);

        txtmaChuyenDe.setEditable(!insertable);
        btnThem.setEnabled(!insertable);
        btnSua.setEnabled(insertable);
        btnXoa.setEnabled(insertable);

        trai1.setEnabled(insertable && !first);
        trai2.setEnabled(insertable && !first);
        phai1.setEnabled(insertable && !last);
        phai2.setEnabled(insertable && !last);
    }

    void first() {
        this.row = 0;
        this.edit();
    }

    void prev() {
        if (this.row > 0) {
            this.row--;
            this.edit();
        }
    }

    void next() {
        if (this.row < tablequanLyNguoiHoc.getRowCount() - 1) {
            this.row++;
            this.edit();
        }
    }

    void last() {
        this.row = tablequanLyNguoiHoc.getRowCount() - 1;
        this.edit();
    }

    boolean kiemThu() {
        if (txtmaChuyenDe.getText().equals("")) {
            DialogHelper.alert(this, "Mã chuyên đề không được bỏ trống");
            return false;
        }
        if (txttenChuyenDe.getText().equals("")) {
            DialogHelper.alert(this, "Tên chuyên đề không được bỏ trống ");
            return false;
        }
        if (txtthoiLuongGio.getText().equals("")) {
            DialogHelper.alert(this, "Thời lượng giờ không được bỏ trống ");
            return false;
        }
        if (txthocPhi.getText().equals("")) {
            DialogHelper.alert(this, "Học phí không được bỏ trống ");
            return false;
        }
        if (txtmaChuyenDe.getText().length() < 5 || txtmaChuyenDe.getText().length() > 5) {
            DialogHelper.alert(this, "Mã chuyên đề phải đúng 5 ký tự");
            return false;
        }
        if (txttenChuyenDe.getText().matches("^[a-zA-Z\\s]+$")) {
            DialogHelper.alert(this, "Tên chuyên đề phải chưa Alphabet và ký tự trắng");
            return false;
        }
        if (lblhinhLogo.getIcon() == null) {
            DialogHelper.alert(this, "Bạn cần thêm hình ảnh");
            return false;
        }
        if (!txtthoiLuongGio.getText().matches("[1-9]\\d*")) {
            DialogHelper.alert(this, "thời lượng giờ phải là số và lớn hơn 0");
            return false;
        }
        if (!txthocPhi.getText().matches("[1-9]\\d*")) {
            DialogHelper.alert(this, "Học phí phải là số và lớn hơn 0");
            return false;
        }

        return true;
    }

}
